version: '3.7'
services:

  building:
    build:
      dockerfile: Dockerfile
      context: ./l2
    volumes:
      - data_volume:/boxfuse-sample-java-war-hello/ddd

  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8080:8080'
    volumes:
      - data_volume:/ddd


volumes:
  data_volume:


