version: '3.7'
services:

  building:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - data_volume:/boxfuse-sample-java-war-hello/ddd

  web:
    depends_on:
      - building
    image: tomcat:alpine
    ports:
      - '8080:8080'
    volumes:
      - data_volume:/ddd


volumes:
  data_volume:


